
haproxy_listen:
  - name: 'stats'
    bind:
      - listen: "{{ hostvars[inventory_hostname]['stats_ip'] }}:9090"
    mode: http
    stats:
      enable: true

haproxy_frontend:
  - name: measure_admin
    bind:
      - listen: "{{ hostvars[inventory_hostname]['stats_ip'] }}:80"
    default_backend: admin_nginx
    mode: http

haproxy_backend:
  - name: admin_nginx
    balance: roundrobin
    mode: http
    option:
      - httpchk GET /healthcheck
    http_request:
      - action: set-header Host yardstickadmin.com
    server:
      - name: admin1
        listen: "192.168.2.184:80"
        param:
          - check
          - slowstart 10s
          - maxconn 16000
          - inter 5s
          - fastinter 500ms
          - downinter 5s
      - name: admin2
        listen: "192.168.2.180:80"
        param:
          - check
          - slowstart 10s
          - maxconn 16000
          - inter 5s
          - fastinter 500ms
          - downinter 5s
