all:
  hosts:
    vagrant: &vagrant
      ansible_port: 2222
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/default/virtualbox/private_key
    playground-haproxy: *vagrant
  children:
    haproxy:
      hosts:
        playground-haproxy:
