all:
  hosts:
    ansible-playground:
      ansible_port: 2222
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/default/virtualbox/private_key
  children:
    load-balancers:
      hosts:
        ansible-playground:
      vars:
        haproxy_listen:
          - name: 'stats'
            bind:
              - listen: "0.0.0.0:9090"
            mode: http
            stats:
              enable: true

        haproxy_frontend:
          - name: measure_admin
            bind:
              - listen: "0.0.0.0:80"
            default_backend: admin_nginx
            mode: http

        haproxy_backend:
          - name: admin_nginx
            balance: roundrobin
            mode: http
            option:
              - httpchk GET /healthcheck
            http_request:
              - action: set-header Host yardstickadmin.com
            server:
              - name: admin1
                listen: "192.168.2.184:80"
                param:
                  - check
                  - slowstart 10s
                  - maxconn 16000
                  - inter 5s
                  - fastinter 500ms
                  - downinter 5s
              - name: admin2
                listen: "192.168.2.180:80"
                param:
                  - check
                  - slowstart 10s
                  - maxconn 16000
                  - inter 5s
                  - fastinter 500ms
                  - downinter 5s
