- hosts: playground-plex
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: marvinpinto.plex
      tags:
        - plex
    - role: keepalived
      keepalived_version: 'v2.0.7'
