keepalived_vrrp_scripts:
  chk_haproxy:
    script: /usr/bin/env
    weight: 2
    interval: 10

keepalived_vrrp_instances:
  VI_1:
    interface: enp0s8
    state: MASTER
    priority: 101
    virtual_router_id: 51

    authentication:
      auth_type: PASS
      auth_pass: '$$f234sfwef'

    virtual_ipaddresses:
      - '192.168.50.50'

    track_scripts:
      - chk_haproxy
