stats_ip: '192.168.50.50'
keepalived_vrrp_scripts:
  chk_haproxy:
    script: '/usr/bin/pgrep haproxy'
    weight: 2
    interval: 1
keepalived_vrrp_instances:
  VI_1:
    interface: enp0s8
    state: MASTER
    priority: 101
    virtual_router_id: 51

    authentication:
      auth_type: PASS
      auth_pass: '4Apr3C*d'

    virtual_ipaddresses:
      - '192.168.50.50'

    track_scripts:
      - chk_haproxy
